'use client'

import { useEffect, useState, Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import type { Petition } from '@/lib/types'
import { getPetition } from '@/lib/actions/petitions'

function PrintPetitionsContent() {
  const [petition, setPetition] = useState<Petition | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  const searchParams = useSearchParams()
  const router = useRouter()
  
  const petitionId = searchParams.get('id')
  const title = searchParams.get('title') || 'Petitions'

  useEffect(() => {
    const loadData = async () => {
      if (!petitionId) {
        setError('No petition ID provided')
        setLoading(false)
        return
      }

      try {
        const petitionData = await getPetition(petitionId)
        if (!petitionData) {
          setError('Petition not found')
        } else {
          setPetition(petitionData)
        }
      } catch (err) {
        console.error('Failed to load petition:', err)
        setError('Failed to load petition for printing')
      } finally {
        setLoading(false)
      }
    }

    loadData()
  }, [petitionId])

  // Auto-print after content loads
  useEffect(() => {
    if (!loading && !error && petition) {
      const timer = setTimeout(() => {
        window.print()
      }, 1000)
      return () => clearTimeout(timer)
    }
  }, [loading, error, petition])

  const handlePrint = () => {
    window.print()
  }

  const handleClose = () => {
    router.back()
  }

  if (loading) {
    return (
      <div>
        <div className="print-preview-notice hide-on-print">
          Loading petition for printing...
        </div>
      </div>
    )
  }

  if (error || !petition) {
    return (
      <div>
        <div className="print-preview-notice hide-on-print" style={{ background: '#ffebee', borderColor: '#f44336', color: '#c62828' }}>
          {error || 'Petition not found'}
        </div>
        <div className="print-actions hide-on-print">
          <button className="print-button secondary" onClick={handleClose}>
            ← Back
          </button>
        </div>
      </div>
    )
  }

  return (
    <div>
      {/* Print Actions - Hidden on Print */}
      <div className="print-actions hide-on-print">
        <button className="print-button secondary" onClick={handleClose}>
          ← Back
        </button>
        <button className="print-button" onClick={handlePrint}>
          🖨️ Print
        </button>
      </div>

      {/* Preview Notice - Hidden on Print */}
      <div className="print-preview-notice hide-on-print">
        Print Preview - This page will automatically print when content finishes loading
      </div>

      {/* Print Header */}
      <div className="print-header">
        <h1 style={{ fontSize: '18pt', margin: '0 0 0.5rem 0', fontWeight: 'bold' }}>
          {title}
        </h1>
        <div style={{ fontSize: '14pt', margin: '0.5rem 0' }}>
          {petition.title}
        </div>
        <div style={{ fontSize: '12pt', color: '#666' }}>
          {new Date(petition.date).toLocaleDateString('en-US', { 
            weekday: 'long', 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}
        </div>
      </div>

      {/* Petitions Content */}
      <div className="petition-section">
        <div>
          {(petition.generated_content || '').split('\n').filter(line => line.trim()).map((petitionText, i) => (
            <div key={i} className="petition-item">
              <div style={{ marginBottom: '0.3rem' }}>
                {petitionText}
              </div>
              <div className="petition-response liturgical-rubric">
                Lord, hear our prayer.
              </div>
            </div>
          ))}
        </div>
        
        {/* Concluding Prayer */}
        <div style={{ marginTop: '2rem', fontSize: '12pt', fontStyle: 'italic' }}>
          <div style={{ marginBottom: '1rem' }}>
            Almighty and eternal God, ruler of all things in heaven and earth: 
            Mercifully accept the prayers of your people, and strengthen us to do your will; 
            through Jesus Christ our Lord.
          </div>
          <div style={{ textAlign: 'right', fontWeight: 'bold' }}>
            Amen.
          </div>
        </div>
      </div>

      {/* Print Footer */}
      <div className="print-footer">
        Generated by Liturgy.Faith • {new Date().toLocaleDateString()}
      </div>
    </div>
  )
}

export default function PrintPetitionsPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <PrintPetitionsContent />
    </Suspense>
  )
}